name: Android-13-Canary-Deployment

on:
  workflow_dispatch:

env:
  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  USER_NAME: ${{ secrets.USER_NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  SF_PWD: ${{ secrets.SF_PWD }}
  RELEASE_TYPE: 'canary'
  ENVIRONMENT_TYPE: ${{ secrets.ENVIRONMENT_TYPE }}
  PACKAGE_LIST: core,basic,omni,stock,full,go,addonsets,addons

jobs:
  build:
    runs-on: macos-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: Setup SSH Keys and known_hosts 
         uses: webfactory/ssh-agent@v0.4.1
         with:
             ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
       - name: Environment Details and clean up
         run: |
            ls -R
            rm -rf build 10 11 12 12.1 Build Releases canary-release release nikgapps.github.io TempPackages overlays_SL overlays_T
       - name: Initialization and Fetching the Source Code
         run: |
            git config --global user.name "$USER_NAME"
            git config --global user.email "$EMAIL"
            git clone git@github.com:nikhilmenghani/build.git
            git clone git@github.com:nikgapps/overlays_T.git
       - name: Installing Requirements
         run: |
            python3 -m pip install wheel setuptools testresources
            cd build
            pip3 install -r requirements.txt
            cd ..
       - name: Update Git configs
         run: |
           git config --global http.postBuffer 157286400

       - name: Building Android T Gapps
         run: |
            cd build
            python3 run.py -A 13 -P $PACKAGE_LIST -G -F
            cd ..
