name: NikGapps-Deployment

on:
  workflow_dispatch:

env:
  RELEASE_TYPE: 'stable'
  PACKAGE_LIST: core

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        android_version:
          - '10'
          - '11'
          - '12.1'
          - '13'

    steps:
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Environment Details and clean up
        run: |
          rm -rf $REPOSITORY 10 11 12 12.1 13 Build Releases canary-release release nikgapps.github.io TempPackages

      - name: Initialization and Fetching the Source Code
        run: |
          git config --global user.name "test"
          git config --global user.email "test@test.com"

      - name: Installing Requirements
        run: |
          sudo apt update ; sudo apt install python3 python3-pip aapt gcc python3-dev git git-lfs openjdk-8-jdk apktool dialog -y
          python3 -m pip install wheel setuptools testresources
          python3 -m pip install NikGapps
          mkdir NikGappsProject

      - name: Update Git configs
        run: |
          git config --global http.postBuffer 157286400

      - name: Building Android Gapps
        run: |
          cd NikGappsProject
          nikgapps --sign --release --androidVersion ${{ matrix.android_version }} --packageList $PACKAGE_LIST
          cd ..
