name: NikGapps-Deployment

on:
  workflow_dispatch:

env:
  RELEASE_TYPE: 'stable'
  PACKAGE_LIST: full

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        android_version:
          - '10'
          - '11'
          - '12.1'
          - '13'

    steps:
      - name: Set Swap
        uses: get-bridge/swap-space-action@v1
        with:
          swap-size-mb: 8192
      - name: Checkout
        uses: actions/checkout@main

      - name: Environment Details and clean up
        run: |
          rm -rf $REPOSITORY 10 11 12 12.1 13 Build Releases canary-release release nikgapps.github.io TempPackages

      - name: Initialization and Fetching the Source Code
        run: |
          git config --global user.name "test"
          git config --global user.email "test@test.com"

      - name: Installing Requirements
        run: |
          python3 -m pip install wheel setuptools testresources
          python3 -m pip install NikGapps
          sudo apt update ; sudo apt install aapt -y
          mkdir NikGappsProject

      - name: Update Git configs
        run: |
          git config --global http.postBuffer 157286400

      - name: Building Android Gapps
        run: |
          cd NikGappsProject
          nikgapps --sign --release --androidVersion ${{ matrix.android_version }} --packageList $PACKAGE_LIST
          cd ..
