name: NikGapps-Deployment

on:
  workflow_dispatch:

env:
  RELEASE_TYPE: 'stable'
  PACKAGE_LIST: core

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Create workspace
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Environment Details and clean up
        run: |
          rm -rf $REPOSITORY 10 11 12 12.1 13 Build Releases canary-release release nikgapps.github.io TempPackages

      - name: Initialization and Fetching the Source Code
        run: |
          git config --global user.name "test"
          git config --global user.email "test@test.com"

      - name: Installing Requirements
        run: |
          python3 -m pip install wheel setuptools testresources
          python3 -m pip install NikGapps
          mkdir NikGappsProject

      - name: Archive home directory
        run: |
          tar -czf workspace.tar.gz -C $HOME .
          mv workspace.tar.gz $HOME/
          
      - name: Upload workspace
        uses: actions/upload-artifact@v2
        with:
          name: workspace
          path: $HOME/workspace.tar.gz

  build:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Download workspace
        uses: actions/download-artifact@v2
        with:
          name: workspace
          path: $HOME/

      - name: Extract workspace
        run: |
          tar -xzf $HOME/workspace.tar.gz -C $HOME/
          rm $HOME/workspace.tar.gz

      - name: Building Android Gapps
        run: |
          cd $HOME/NikGappsProject
          nikgapps --sign --release --androidVersion ${{ matrix.android_version }} --packageList $PACKAGE_LIST
          cd $HOME
