name: NikGapps-Deployment

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' 

env:
  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  REPOSITORY: ${{ secrets.REPOSITORY }}
  USER_NAME: ${{ secrets.USER_NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  SOURCE: ${{ secrets.SOURCE }}
  WEBSITE: ${{ secrets.WEBSITE }}
  RELEASE: ${{ secrets.RELEASE }}

jobs:
  build:
    runs-on: macos-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: Setup SSH Keys and known_hosts 
         uses: webfactory/ssh-agent@v0.4.1
         with:
             ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
       - name: Environment Details and clean up
         run: |
           rm -rf $REPOSITORY 10 11 Build Releases $SOURCE $WEBSITE $RELEASE
       - name: Initialization and Fetching the Source Code
         run: |
            git config --global user.name "$USER_NAME"
            git config --global user.email "$EMAIL"
            git clone $SOURCE
       - name: Installing Requirements
         run: |
            python3 -m pip install wheel setuptools testresources
            cd $REPOSITORY
            pip3 install -r requirements.txt
            cd ..
       - name: Get Website and Release Source
         run: |
           git clone --depth=1 $WEBSITE
           git clone --depth=1 $RELEASE
#        - name: Fetching Android Q source
#          run: |
#              git config --global http.postBuffer 157286400
#              git clone --depth=1 https://gitlab.com/nikgapps/10.git
#        - name: Building Android Q Gapps
#          run: |
#             cd $REPOSITORY
#             python3 main.py 10 go,core,basic,omni,stock,full,addons,addonsets
#             cd ..
       - name: Fetching Android R source
         run: |
              git config --global http.postBuffer 157286400
              git clone --depth=1 https://gitlab.com/nikgapps/11.git
       - name: Building Android R Gapps
         run: |
            cd $REPOSITORY
            python3 main.py 11 core
            cd ..
