name: NikGapps-Deployment

on:
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

env:
  RELEASE_TYPE: 'stable'
  ENVIRONMENT_TYPE: production
  PACKAGE_LIST: core,basic,omni,stock,full,go,addonsets,addons
  UPLOAD_RELEASE: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: Https
         run: |
            git config --global url."https://github.com/".insteadOf git@github.com:
            
       - name: Environment Details and clean up
         run: |
            sudo apt install default-jre adb aapt -y
            ls -R
            rm -rf build 10 11 12 12.1 13 Build Releases canary-release release nikgapps.github.io TempPackages overlays_SL overlays_T
       - name: Initialization and Fetching the Source Code
         run: |
            git clone git@github.com:nikgapps/build.git
       - name: Installing Requirements
         run: |
            python3 -m pip install wheel setuptools testresources
            cd build
            pip3 install -r requirements.txt
            cd ..
       - name: Get Website and Release Source
         run: |
           git clone --depth=1 git@github.com:nikgapps/nikgapps.github.io.git
           git clone git@github.com:nikgapps/release.git
           
       - name: Update Git configs
         run: |
           git config --global http.postBuffer 157286400
       - name: Release info
         run: |
            echo Test >> release.txt
            
       - name: Remove old Releases
         uses: dev-drprasad/delete-older-releases@v0.1.0
         if: env.UPLOAD_RELEASE == 'true' && !cancelled()
         with:
           keep_latest: 0
           delete_tags: true
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
           
       - name: Generate release tag A10
         id: tag1
         if: env.UPLOAD_RELEASE == 'true' && !cancelled()
         run: |
           echo "::set-output name=release_tag::Android-10"
           echo "::set-output name=status::success"
       - name: Generate release tag A11
         id: tag2
         if: env.UPLOAD_RELEASE == 'true' && !cancelled()
         run: |
           echo "::set-output name=release_tag::Android-11"
           echo "::set-output name=status::success"
       - name: Generate release tag A12
         id: tag3
         if: env.UPLOAD_RELEASE == 'true' && !cancelled()
         run: |
           echo "::set-output name=release_tag::Android-12"
           echo "::set-output name=status::success"
       - name: Generate release tag A12.1
         id: tag4
         if: env.UPLOAD_RELEASE == 'true' && !cancelled()
         run: |
           echo "::set-output name=release_tag::Android-12.1"
           echo "::set-output name=status::success"
           
       - name: Generate release tag A13
         id: tag5
         if: env.UPLOAD_RELEASE == 'true' && !cancelled()
         run: |
           echo "::set-output name=release_tag::Android-13"
           echo "::set-output name=status::success"
       - name: Download Config
         run: |
            rm -r ./build/Config.py
            wget https://gist.githubusercontent.com/Bartixxx32/0e23bb34ca57e6ee5ea72e80cc13f3e6/raw/4ea5fec60e0cef4c9846c1cd8a0b44f1e52e9eee/Config.py -O ./build/Config.py

       - name: Building Android 10 Gapps
         run: |
            rm -rf 10 11 12 12.1 13 Releases canary-release release nikgapps.github.io TempPackages overlays_SL overlays_T
            cd build
            python3 run.py -A 10 -P $PACKAGE_LIST -G -F
            cd ..
            
       - name: Upload gapps A10
         uses: softprops/action-gh-release@v1
         if: steps.tag1.outputs.status == 'success' && !cancelled()
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ steps.tag1.outputs.release_tag }}
           body_path: release.txt
           files: /home/runner/work/deploy/deploy/Releases/10/*
           
       - name: Building Android 11 Gapps
         run: |
            rm -rf 10 11 12 12.1 13 Releases canary-release release nikgapps.github.io TempPackages overlays_SL overlays_T
            cd build
            python3 run.py -A 11 -P $PACKAGE_LIST -G -F
            cd ..
            
       - name: Upload gapps A11
         uses: softprops/action-gh-release@v1
         if: steps.tag2.outputs.status == 'success' && !cancelled()
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ steps.tag2.outputs.release_tag }}
           body_path: release.txt
           files: /home/runner/work/deploy/deploy/Releases/11/*
           
       - name: Building Android 12 Gapps
         run: |
            rm -rf 10 11 12 12.1 13 Releases canary-release release nikgapps.github.io TempPackages overlays_SL overlays_T
            cd build
            python3 run.py -A 12 -P $PACKAGE_LIST -G -F
            cd ..
      
       - name: Upload gapps A12
         uses: softprops/action-gh-release@v1
         if: steps.tag3.outputs.status == 'success' && !cancelled()
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ steps.tag3.outputs.release_tag }}
           body_path: release.txt
           files: /home/runner/work/deploy/deploy/Releases/12/*
           
       - name: Building Android 12.1 Gapps
         run: |
            rm -rf 10 11 12 12.1 13 Releases canary-release release nikgapps.github.io TempPackages overlays_SL overlays_T
            cd build
            python3 run.py -A 12.1 -P $PACKAGE_LIST -G -F
            cd ..
            
       - name: Upload gapps A12.1
         uses: softprops/action-gh-release@v1
         if: steps.tag4.outputs.status == 'success' && !cancelled()
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ steps.tag4.outputs.release_tag }}
           body_path: release.txt
           files: /home/runner/work/deploy/deploy/Releases/12.1/*
       
       - name: Building Android 13 Gapps
         run: |
            rm -rf 10 11 12 12.1 13 Releases canary-release release nikgapps.github.io TempPackages overlays_SL overlays_T
            cd build
            python3 run.py -A 13 -P $PACKAGE_LIST -G -F
            cd ..

       - name: Upload gapps A13
         uses: softprops/action-gh-release@v1
         if: steps.tag5.outputs.status == 'success' && !cancelled()
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ steps.tag5.outputs.release_tag }}
           body_path: release.txt
           files: /home/runner/work/deploy/deploy/Releases/13/*
         
