name: Sync Operation

on:
  workflow_dispatch:

env:
  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  USER_NAME: ${{ secrets.USER_NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  SF_PWD: ${{ secrets.SF_PWD }}
  RELEASE_TYPE: 'stable'
  ENVIRONMENT_TYPE: ${{ secrets.ENVIRONMENT_TYPE }}

jobs:
  build:
    runs-on: macos-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: Setup SSH Keys and known_hosts 
         uses: webfactory/ssh-agent@v0.4.1
         with:
             ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
       - name: Environment Details and clean up
         run: |
            ls -R
            rm -rf build
       - name: Initialization and Fetching the Source Code
         run: |
            git config --global user.name "$USER_NAME"
            git config --global user.email "$EMAIL"
            git clone git@github.com:nikgapps/build.git
       - name: Installing Requirements
         run: |
            python3 -m pip install wheel setuptools testresources
            cd build
            pip3 install -r requirements.txt
            cd ..
       - name: Update Git configs
         run: |
           git config --global http.postBuffer 157286400

       - name: Syncing Sources
         run: |
            cd build
            python3 cleanup.py
            python3 pe_sync.py -A 13
            python3 nikgapps_sync.py -A 10,11,12,12.1,13
            cd ..
